Changes and additions to make MEGA65 work on the Wukong V2 board.
MEGA65/mega65-core pull request #808
Opened 2024-07-15 11:16 UTC by 0xa000

This PR introduces various changes and additions to make MEGA65 work on the QMTECH Wukong V2 board. The Wukong top-level VHDL file is based on the latest R6 top-level VHDL file, with all non-supported peripherals removed or disabled. 

Changes outside of the Wukong top-level file have been kept to a minimum, so as not to impact other cores:

- A number of signals related to the Ethernet controller in iomapper.vhdl have been assigned a default value, such that the CPU does not lock up when not generating the Ethernet controller.
- The portb_pins signal has been changed from "in" to "inout" to allow the newly added physical keyboard scanner for Wukong to drain remaining charge on the keyboard pins.
- The 50 MHz versions of the clock and audio clock generation logic have been updated. Since AFAIK at the moment Wukong is the only target using these files, this should not affect any other cores.

Peripherals known to work with this core:

- Physical C64 keyboard attached to the 40-pin user GPIO header (J12).
- Joysticks 1 and 2 attached to the two PMOD ports (wired as for Nexys).
- Internal SD-card.
- Serial monitor.
- HDMI video including sound (sound does not work on all monitors).
- QSPI flash.

Known issues:

- Xanadu assembly demo shows black "barcodes"; not sure if that's supposed to happen.
- Megaflash does not support the QSPI flash device for this board, so the core hangs when going into the flash menu. This will be fixed when branch "782-mflash-lowlevel" is merged into development.

2024-07-17 23:26 UTC, benitoss commented
If the Wukong V2 board has SDRAM, Why don't you include the SDRAM as Attic RAM in the new version of the core?

2024-07-19 10:11 UTC, 0xa000 commented
Indeed, the Wukong has a 256MB DDR3 SDRAM on the board itself. I'd love to include that as Attic RAM, but I don't know how to implement a DDR3/SDRAM controller in VHDL and integrate it with the MEGA65 core.

2024-07-25 07:33 UTC, MJoergen commented
> Indeed, the Wukong has a 256MB DDR3 SDRAM on the board itself. I'd love to include that as Attic RAM, but I don't know how to implement a DDR3/SDRAM controller in VHDL and integrate it with the MEGA65 core.

Well, I have an SDRAM controller tested on the R6 board that you may use freely: https://github.com/MJoergen/SDRAM

2024-07-25 07:38 UTC, lydon42 requested changes
Currently the change messes up the keyboard of the MEGA65 PCBs.
We need to find a way to mitigate this.

2024-08-04 08:47 UTC, gardners commented
I'm working on resolving the regression for non-wukong platforms by pushing the portb charge logic to the edge of the design with a dedicated signal. Also simplifying the wukong scan logic and improving debounce.  This should be tested on a wukong board to make sure I haven't regressed anything there.

2024-08-04 10:26 UTC, lydon42 commented
Paul has made a workaround that apparently makes the keyboard work on r6 again. You need to check if wukong also still works.
You can get the core here: https://builder.mega65.org/job/mega65-core/job/808-804-wukong-mkii-kbd-merge/

2024-08-04 16:00 UTC, lydon42 commented
Merged into 804-808-mkii-kbd-wukong-newcore.

2024-08-04 16:00 UTC, closed without merging